---

- name: create config directory
  ansible.builtin.file:
    name: /etc/mariadb_backup
    state: directory
    mode: "0750"

- name: create backup directory
  ansible.builtin.file:
    name: '{{ mariadb_backup_backup_directory }}'
    state: directory
    mode: "0755"

# - name: copy distributed config
#   ansible.builtin.copy:
#     src: "{{ mariadb_backup_download_directory }}/mariadb_backup.conf"
#     dest: /etc/mariadb_backup/mariadb_backup.conf-DIST
#     remote_src: true
#     mode: "0640"
#   when:
#     - mariadb_backup_download

- name: merge mariadb_backup configuration between defaults and custom
  ansible.builtin.set_fact:
    mariadb_backup_connection: "{{ mariadb_backup_defaults_connection | combine(mariadb_backup_connection, recursive=True) }}"
    mariadb_backup_notification: "{{ mariadb_backup_defaults_notification | combine(mariadb_backup_notification, recursive=True) }}"
    mariadb_backup_stoarge: "{{ mariadb_backup_defaults_stoarge | combine(mariadb_backup_stoarge, recursive=True) }}"
    mariadb_backup_exclude: "{{ mariadb_backup_defaults_exclude | combine(mariadb_backup_exclude, recursive=True) }}"
    mariadb_backup_include: "{{ mariadb_backup_defaults_include | combine(mariadb_backup_include, recursive=True) }}"
    mariadb_backup_cron: "{{ mariadb_backup_defaults_cron | combine(mariadb_backup_cron, recursive=True) }}"

- name: create config
  ansible.builtin.template:
    src: mariadb_backup.yml.j2
    dest: /etc/mariadb_backup/mariadb_backup.yml
    mode: "0640"

- name: remove pre running script
  ansible.builtin.file:
    name: "{{ mariadb_backup_pre_script.file }}"
    state: absent
  when:
    - mariadb_backup_pre_script.content is defined
    - mariadb_backup_pre_script.content | length == 0
    - mariadb_backup_pre_script.file is defined
    - mariadb_backup_pre_script.file | length != 0

- name: remove post running script
  ansible.builtin.file:
    name: "{{ mariadb_backup_post_script.file }}"
    state: absent
  when:
    - mariadb_backup_post_script.content is defined
    - mariadb_backup_post_script.content | length == 0
    - mariadb_backup_post_script.file is defined
    - mariadb_backup_post_script.file | length != 0

- name: create pre running script
  ansible.builtin.copy:
    dest: "{{ mariadb_backup_pre_script.file }}"
    content: "{{ mariadb_backup_pre_script.content }}"
    mode: "0755"
  when:
    - mariadb_backup_pre_script.content is defined
    - mariadb_backup_pre_script.content | length != 0
    - mariadb_backup_pre_script.file is defined
    - mariadb_backup_pre_script.file | length != 0

- name: create post running script
  ansible.builtin.copy:
    dest: "{{ mariadb_backup_post_script.file }}"
    content: "{{ mariadb_backup_post_script.content }}"
    mode: "0755"
  when:
    - mariadb_backup_post_script.content is defined
    - mariadb_backup_post_script.content | length != 0
    - mariadb_backup_post_script.file is defined
    - mariadb_backup_post_script.file | length != 0
