---

- name: merge mariadb_backup configuration between defaults and custom
  ansible.builtin.set_fact:
    mariadb_backup_cron: "{{ mariadb_backup_defaults_cron | combine(mariadb_backup_cron, recursive=True) }}"

- name: remove background cron job
  when:
    - not mariadb_backup_cron.enabled | default('false') | bool
    - mariadb_backup_cron.type | default('cron') | string | lower in ["cron", "systemd"]
  block:
    - name: remove cron jobs
      when:
        - not mariadb_backup_cron.type | default('cron') | string == "cron"
      block:
        - name: remove cron job for background jobs
          ansible.builtin.cron:
            name: automatic mysql backup
            job: /usr/local/bin/mariadb_backup.py
            user: root
            cron_file: mariadb_backup
            state: absent
          failed_when: false

        - name: disable mariadb-backup.service
          ansible.builtin.service:
            name: mariadb-backup.service
            enabled: false
          failed_when: false

        - name: disable systemd timer
          ansible.builtin.service:
            name: mariadb-backup.timer
            enabled: false
            state: stopped
          failed_when: false

- name: create background cron job
  when:
    - mariadb_backup_cron.enabled | default('false') | bool
    - mariadb_backup_cron.type | default('cron') |  string | lower in ["cron", "systemd"]
  block:
    - name: remove cron file
      when:
        - not mariadb_backup_cron.type | default('cron') | string == "cron"
      block:
        - name: remove cron job for background jobs
          ansible.builtin.cron:
            name: automatic mysql backup
            job: /usr/local/bin/mariadb_backup.py
            user: root
            cron_file: mariadb_backup
            state: absent
          failed_when: false

    - name: remove system unit file
      when:
        - not mariadb_backup_cron.type | default('cron') | string == "systemd"
      block:
        - name: disable mariadb_backup background timer
          ansible.builtin.service:
            name: mariadb-backup.timer
            enabled: false
            state: stopped
          failed_when: false

    - name: cron daemon
      when:
        - mariadb_backup_cron.enabled | default('false') | bool
        - mariadb_backup_cron.daemon | default('') | string | length > 0
        - mariadb_backup_cron.type | default('cron') | string == "cron"
      block:
        - name: ensure cron daemon is installed
          ansible.builtin.package:
            name: "{{ mariadb_backup_cron.daemon }}"
            state: present

        - name: create cron job for background jobs
          ansible.builtin.cron:
            name: automatic mysql backup
            job: "/usr/local/bin/mariadb_backup.py --directory {{ mariadb_backup_backup_directory }} --config /etc/mariadb_backup/mariadb_backup.yml"
            minute: "{{ mariadb_backup_cron.minute | default('58') }}"
            hour: "{{ mariadb_backup_cron.hour | default('2') }}"
            weekday: "{{ mariadb_backup_cron.weekday | default('*') }}"
            user: root
            cron_file: mariadb_backup
            state: present

    - name: systemd unit
      when:
        - mariadb_backup_cron.enabled | default('false') | bool
        - mariadb_backup_cron.type | default('cron') | string == "systemd"
      block:
        - name: create mariadb-backup run configuration
          ansible.builtin.template:
            src: etc/default/mariadb-backup.j2
            dest: "{{ mariadb_backup_defaults_directory }}/mariadb-backup"
            force: true
            owner: root
            group: root
            mode: "0640"

        - name: create systemd unit file
          ansible.builtin.template:
            src: etc/init/systemd/mariadb-backup.service.j2
            dest: "{{ systemd_lib_directory }}/mariadb-backup.service"
            mode: "0644"
          notify:
            - daemon reload

        - name: create systemd timer file
          ansible.builtin.template:
            src: etc/init/systemd/mariadb-backup.timer.j2
            dest: "{{ systemd_lib_directory }}/mariadb-backup.timer"
            mode: "0644"
          notify:
            - daemon reload

        - name: flush handlers
          ansible.builtin.meta: flush_handlers

        - name: ensure mariadb-backup.service enabled
          ansible.builtin.service:
            name: mariadb-backup.service
            enabled: true

        - name: enable mariadb_backup background timer
          ansible.builtin.service:
            name: mariadb-backup.timer
            enabled: true
            state: started

...
