---

- name: create download directory
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ mariadb_backup_local_tmp_directory }}"
    state: directory
    mode: "0750"

- name: clone mariadb_backup repository to ansible-host
  when:
    - mariadb_backup_source == "git"
  block:
    - name: create local temp directory
      become: false
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup/{{ mariadb_backup_version }}"
        state: directory
        mode: "0750"

    - name: download git sources to local directory
      become: false
      delegate_to: localhost
      ansible.builtin.git:
        repo: "{{ mariadb_backup_git.repository }}"
        version: "{{ mariadb_backup_git.version | default('master') }}"
        dest: "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup/{{ mariadb_backup_version }}"
        depth: 1
        update: true
        force: true

    - name: create transfer archive
      become: false
      delegate_to: localhost
      community.general.archive:
        path: "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup/{{ mariadb_backup_version }}"
        dest: "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup_{{ mariadb_backup_version }}.zip"
        mode: "0660"
        remove: false
        format: zip
        exclude_path:
          - "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup/{{ mariadb_backup_version }}/.git*"
        exclusion_patterns:
          - "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup/{{ mariadb_backup_version }}/.git*"

    - name: define mariadb_backup download directory
      ansible.builtin.set_fact:
        mariadb_backup_download_directory: "/tmp/mariadb_backup/{{ mariadb_backup_version }}"

- name: download mariadb_backup archive to ansible-host
  when:
    - mariadb_backup_source == "archive"
  block:
    - name: detect the downloaded mariadb_backup archive
      become: false
      delegate_to: localhost
      run_once: true
      ansible.builtin.stat:
        path: "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup_{{ mariadb_backup_version }}.zip"
      register: stat_mariadb_backup_archive

    - name: download mariadb_backup archive
      when:
        - stat_mariadb_backup_archive.stat is defined
        - not stat_mariadb_backup_archive.stat.exists | default('false')
      become: false
      delegate_to: localhost
      run_once: true
      ansible.builtin.get_url:
        url: "{{ mariadb_backup_archive }}"
        dest: "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup_{{ mariadb_backup_version }}.zip"
        mode: "0640"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: define mariadb_backup download directory
      ansible.builtin.set_fact:
        mariadb_backup_download_directory: "/tmp/mariadb_backup/{{ mariadb_backup_version }}"

- name: propagate mariadb_backup.zip
  become: true
  ansible.builtin.copy:
    src: "{{ mariadb_backup_local_tmp_directory }}/mariadb_backup_{{ mariadb_backup_version }}.zip"
    dest: /tmp
    mode: "0640"

- name: create temp directory
  ansible.builtin.file:
    path: /tmp/mariadb_backup
    state: directory
    mode: "0750"

- name: extract mariadb_backup.zip
  ansible.builtin.unarchive:
    src: "/tmp/mariadb_backup_{{ mariadb_backup_version }}.zip"
    dest: /tmp/mariadb_backup
    remote_src: true
