---
namespace: bodsch
name: database

version: 2.5.0

readme: README.md

authors:
  - Bodo Schulz <bodo@boone-schulz.de>

description: collection of database modules

license:
  - Apache-2.0

license_file: ''

tags: []

dependencies:
 community.crypto: "*"
 ansible.utils: "*"

repository: https://github.com/bodsch/ansible-collection-database
documentation: https://github.com/bodsch/ansible-collection-database/README.md
homepage: https://github.com/bodsch/ansible-collection-database
issues: https://github.com/bodsch/ansible-collection-database/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
