---
namespace: bodsch
name: database

version: 2.0.0

readme: README.md

authors:
  - Bodo Schulz <bodo@boone-schulz.de>

description: A collection of Ansible roles to manage databases

license:
  - Apache-2.0

license_file: ''

tags:
  - linux
  - databases

dependencies:
  ansible.mysql: ">=5.0"
  ansible.posix: ">=2.2"
  bodsch.core: ">=2.13.5"
  bodsch.scm: ">=1.11.0"
  bodsch.systemd: ">=1.5.0"
  community.general: "*"
  community.postgresql: ">=4.2"

repository: https://github.com/bodsch/ansible-collection-database
documentation: https://github.com/bodsch/ansible-collection-database/README.md
homepage: https://github.com/bodsch/ansible-collection-database
issues: https://github.com/bodsch/ansible-collection-database/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
