---

- name: use external repository
  when:
    - mariadb_use_external_repo | default(false) | bool
  block:

    - name: define distibution family for debian
      when:
        - ansible_facts.distribution | lower == 'debian'
      ansible.builtin.set_fact:
        mariadb_distribution_family: "{{ ansible_facts.os_family | lower }}"

    - name: define distibution family for ubuntu
      when:
        - ansible_facts.distribution | lower == 'ubuntu'
      ansible.builtin.set_fact:
        mariadb_distribution_family: "{{ ansible_facts.distribution | lower }}"

    - name: use external repository
      bodsch.core.apt_sources:
        name: mariadb
        filename: mariadb.sources
        uris:
          - "{{ mariadb_debian_repo }}/mariadb-server/{{ mariadb_version }}/repo/{{ mariadb_distribution_family }}"
          - "{{ mariadb_debian_repo }}/maxscale/latest/apt"
        suites: "{{ ansible_facts.distribution_release }}"
        components:
          - main
        signed_by: /usr/share/keyrings/mariadb-keyring-2025.gpg
        key:
          method: download
          url: "https://supplychain.mariadb.com/mariadb-keyring-2025.gpg"
          dest: "/usr/share/keyrings/mariadb-keyring-2025.gpg"
          dearmor: true
          validate: true
        update_cache: true

- name: remove external repository
  when:
    - not mariadb_use_external_repo | default(false) | bool
  ansible.builtin.file:
    state: absent
    path: /etc/apt/sources.list.d/mariadb.sources
  register: apt_ext_repo
  changed_when: apt_ext_repo.changed
  failed_when: apt_ext_repo.failed

- name: update package cache
  ansible.builtin.package:
    update_cache: true
  when:
    - apt_ext_repo.changed

...
