---

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: enable mariadb service
  ansible.builtin.service:
    name: '{{ mariadb_service }}'
    enabled: true
  when:
    - not running_in_check_mode

...
