---

mariadb_backup_version: 2.0.0

mariadb_backup_backup_directory: /srv/backup/mariadb

mariadb_backup_release: {}
  # download_url: https://github.com/bodsch/mariadb-backup/releases
  # file: mariadb-backup_{{ mariadb_backup_version }}_{{ ansible_facts.system | lower }}_{{ system_architecture }}.tar.gz
  # checksum: mariadb-backup_{{ mariadb_backup_version }}_{{ ansible_facts.system | lower }}_{{ system_architecture }}.tar.gz.sha256
  # binary: mariadb-backup

mariadb_backup_direct_download: false

mariadb_backup_connection:
  encrypted_login: false
  username: ''
  password: ''
  host: ''
  port: ''
  socket: /run/mysqld/mysqld.sock
  commpress_communication: true
  login_cnf_file: ''
  use_ssl: false
  max_allowed_packet: ''
  single_transaction: true

# notifications
mariadb_backup_notification:
  enabled: false
  smtp:
    server_name: ""             # smtp.example.com
    port: ""                    # 587
    tls: false
    auth:
      username: ""
      password: ""
  sender: ""                    # backup@example.com
  recipient: ""                 # admin@foo.bar

mariadb_backup_storage:
  destination: "/srv/backup"
  rotation:
    # Set rotation of daily backups. VALUE*24hours
    # If you want to keep only today's backups, you could choose 1,
    # i.e. everything older than 24hours will be removed.
    daily: 2
    weekly: 2

mariadb_backup_exclude:
  databases:
    - performance_schema
    - information_schema
  tables: []

mariadb_backup_include:
  databases: []
  tables: []

mariadb_backup_cron:
  type: systemd          # alternative: cron
  daemon: ""             # "{{ 'cron' if ansible_facts.os_family | lower == 'debian' else 'cronie' }}"
  enabled: true          # [true, false]
  minute: "58"           # 58
  hour: "2"              # 2
  weekday: [ 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
