---

mariadb_root_password: "{{ vault__database.passwords.root }}"
mariadb_root_password_update: true

# mariadb_hostname: "%"

mariadb_databases:
  - name: "{{ database_schema }}"

mariadb_users:
  - name: "backup"
    host: "%"
    password: "{{ vault__database.passwords.backup }}"
    priv:
      "*.*": "SELECT, SHOW DATABASES, SHOW VIEW, EVENT, PROCESS"
    encrypted: false
  - name: "{{ database_user }}"
    host: "%"
    password: "{{ vault__database.passwords.demo }}"
    priv: "{{ database_user }}.*:ALL"
    encrypted: false

mariadb_config_mysqld:
  bind-address: 0.0.0.0
  socket: "{{ mariadb_socket }}"
  skip-external-locking:
  skip-name-resolve: 1
  performance_schema: 1
  expire_logs_days: 2
  max_connections: 20

...
