---

mariadb_backup_connection:
  encrypted_login: false
  username: 'backup'
  password: "{{ vault__database.passwords.backup }}"
  host: "{{ database_hostname }}"
  port: 3306
  socket: "" # /run/mysqld/mysqld.sock
  commpress_communication: true
  login_cnf_file: ''
  use_ssl: false
  max_allowed_packet: ''
  single_transaction: true

mariadb_backup_cron:
  type: systemd       # alternative: systemd
  enabled: true       # [true, false]
  minute: "50"        # 58
  hour: "4"           # 2

mariadb_backup_include:
  databases:
    - demo

mariadb_backup_exclude:
  databases:
    - sys
